name: UserFeedFramework

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build & Test
        run: |
          xcodebuild clean test \
            -project UserFeedFramework/UserFeedFramework.xcodeproj \
            -scheme UserFeedFramework \
            -destination "platform=iOS Simulator,OS=latest,name=iPhone 17"
